### PR TITLE
Casson viscosity model is added

### PR DESCRIPTION
**Pull request by SvensenSeven**
Added Casson viscosity model for non-Newtonian fluid

### CODE REVIEW

**Comment by OpenFOAM** [comment]
For details of how to contribute to OpenFOAM please see:

http://openfoam.org/dev/how-to-contribute/

and please contact the OpenFOAM Foundation to arrange the contributor agreement:

http://openfoam.org/contact/

**Comment by OpenFOAM** [comment]
Could you  update your contribution to conform to the OpenFOAM style-guide:

http://openfoam.github.io/Documentation-dev/html/codingStyleGuide.html

in particular the code you propose is indented with tabs, has trailing whitespace and operators are spaced in a non-standard manner.

**Comment by SvensenSeven** [comment]
Yes, sure. I will do it today

**Comment by OpenFOAM** [comment]
Merged: commit ab205d2e94c8062de64aea1e61b5caaa60609c94

**Pull request closed without merging**
